<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>RoleRun.ExtractGen5BagLayout</AssemblyName>
    <RootNamespace>RoleRun.ExtractGen5BagLayout</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="PKHeX.Core">
      <HintPath>..\engine\publish\PKHeX.Core.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
